sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable
      - lib32stdc++6
      - lib32z1

before_install:
  - nvm install node
  - nvm use node
  - npm install -g --no-progress cordova eslint ionic karma-cli node-sass phantomjs-prebuilt protractor stylelint tslint typescript
  - ionic state clear

install: npm install --no-progress

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test      # unit tests
  - npm run e2e   # run e2e tests against ionic

#after_success:
  # Send coverage info off to cloud ppl
  #- ./node_modules/.bin/codecov
