sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable
      - lib32stdc++6
      - lib32z1

language: node_js
node_js: 6
cache: node_modules
#cache: yarn

before_install:
  - nvm install node
  - nvm use node
  - npm install --global --no-progress --silent codeclimate-test-reporter cordova eslint ionic karma-cli node-sass phantomjs-prebuilt protractor stylelint tslint typescript
#  - yarn global add --no-progress codeclimate-test-reporter cordova eslint ionic karma-cli node-sass phantomjs-prebuilt protractor stylelint tslint typescript
#  - '[ ! -d platforms ] && mkdir platforms'
#  - '[ ! -d plugins ] && mkdir plugins'
  - ionic state clear

install:
  - npm install --no-progress --silent
#  - yarn --no-progress
  - ionic platform add android

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test      # unit tests
  - ionic build android --prod
  - npm run e2e   # run e2e tests against ionic

after_success:
  - codeclimate-test-reporter < coverage/lcov
